spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create   # (create, update, none 등 선택 가능)
    show-sql: true       # 콘솔에 SQL 출력
message:
  sms:
    provider: console
security:
  jwt:
    secret: "dev-secret-dev-secret-dev-secret-dev-secret"
    access-exp-seconds: 3600

image:
  provider: console